# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AppEEARSDialog
                                 A QGIS plugin
 AppEEARS Plugin for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-26
        git sha              : $Format:%H$
        copyright            : (C) 2024 by NASA Earthdata LPDAAC
        email                : lpdaac@usgs.gov
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import QgsApplication, QgsAuthManager, QgsAuthMethodConfig, Qgis, QgsMessageLog, QgsRasterLayer, QgsProject
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .appeears.auth import store_creds_netrc, retrieve_stored_creds, get_appeears_token, NetrcConflictError
from .appeears.utils import fetch_task_data, fetch_bundle_data, build_file_url, set_gdal_options

# Load .ui file so that PyQt can populate plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'appeears_qgis_dialog_base.ui'))

class AppEEARSDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(AppEEARSDialog, self).__init__(parent)
        
        # Set default parameters
        self.api_url = 'https://appeears.earthdatacloud.nasa.gov/api/'
        self.token = None 
        self.current_task_id = None

        # Set up UI
        self.setupUi(self)

        # Connect Signals
        self.save_credentials_pushButton.clicked.connect(self.store_entered_credentials)
        self.refresh_pushButton.clicked.connect(self.refresh_tasks)
        self.select_pushButton.clicked.connect(self.select_task)
        self.load_data_pushButton.clicked.connect(self.load_selected_file)

        # Configure table selection behavior
        self.task_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.task_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bundle_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bundle_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        
    def store_entered_credentials(self):
        """
        Stores lineEdit credentials into the .netrc file.
        """
        machine = 'urs.earthdata.nasa.gov'
        username = self.username_lineEdit.text().strip()
        password = self.password_lineEdit.text().strip()

        # Add to .netrc file
        try:
            store_creds_netrc(machine, username, password)
            QtWidgets.QMessageBox.information(self, "Credentials Updated", f"Credentials for '{machine}' stored successfully.")
        except NetrcConflictError:
            # This means the credentials existed for the given machine
            reply = QtWidgets.QMessageBox.question(self, "Credentials Exist", f"Credentials for '{machine}' already exist. Overwrite them?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.No)

            if reply == QtWidgets.QMessageBox.No:
                return
        
            try:
                store_creds_netrc(machine, username, password, force_update=True)
                QtWidgets.QMessageBox.information(self, "Credentials Updated", f"Credentials for '{machine}' updated successfully.")
            
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Error", str(e))

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Error", str(e))

    def get_token(self, refresh=False):
        """
        Uses functions from the auth module to get a token or refresh.
        """
        machine = 'urs.earthdata.nasa.gov'

        if self.token and not refresh:
            return self.token
        
        username, password = retrieve_stored_creds(machine)

        if not username or not password:
            QtWidgets.QMessageBox.warning(self, "No Credentials", f"No credentials", f"No credentials found for {machine}. Please enter credentials on the login tab.")
            return None
        
        try: 
            new_token = get_appeears_token(self.api_url, machine, username, password)
            self.token = new_token
            return self.token
        
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Token Error", str(e))
            return None


    def refresh_tasks(self):
        """
        Runs upon click of refresh button - gets an appeears token if necessary and populates tasks table.
        """
        
        self.token = self.get_token()
        data_list = fetch_task_data(self.api_url, self.token)
        if not data_list:
            self.token = self.get_token(refresh=True)
            data_list = fetch_task_data(self.api_url, self.token)
            if not data_list:
                QgsMessageLog.logMessage(message="No data retrieved from AppEEARS API or failed to load data.", tag="AppEEARS", level=Qgis.Info)
                return
        self.populate_table(data_list)
        QgsMessageLog.logMessage(message="Populated Task Table", tag="AppEEARS", level=Qgis.Info)

    def populate_table(self, data_list):
        """"
        Populate the tasks table widget from a list of dicts using only
        the desired keys.
        """    

        DESIRED_COLUMNS = ["task_name","status", "task_type", "task_id"]
        num_rows = len(data_list)
        num_cols = len(DESIRED_COLUMNS)
        
        # Clear existing rows
        self.task_tableWidget.clearContents()
        self.task_tableWidget.setRowCount(num_rows)
        self.task_tableWidget.setColumnCount(num_cols)

        # Set Header Labels
        self.task_tableWidget.setHorizontalHeaderLabels(DESIRED_COLUMNS)

        # Populate Table
        for row_index, entry in enumerate(data_list):
            for col_index, key in enumerate(DESIRED_COLUMNS):
                value = entry.get(key,"")
                item = QtWidgets.QTableWidgetItem(str(value))
                self.task_tableWidget.setItem(row_index, col_index, item)
        # Resize
        self.task_tableWidget.resizeColumnsToContents()
    
    def select_task(self):
        """
        Selects the currently highlighted row from the task table, and use it to populate the bundle table.
        """

        #TODO Add some logic to limit selection to 'done' (not expired or in progress)

        row = self.task_tableWidget.currentRow()
        if row < 0:
            print("No row is currently selected.")
            return
        
        # Set task_id using hard-coded task-id column
        self.current_task_id = self.task_tableWidget.item(row,3).text()
        
        if not self.current_task_id:
            QtWidgets.QMessageBox.warning(self, "Invalid Row","Could not find task.")
            return

        # Fetch bundle data from AppEEARS API
        bundle_data = fetch_bundle_data(self.api_url, self.token, self.current_task_id)

        if not bundle_data:
            QgsMessageLog.logMessage(message=f"Error fetching bundle data.", tag="AppEEARS", level=Qgis.Info)

        # Populate Bundle Table
        self.populate_bundle_table(bundle_data)
        
    def populate_bundle_table(self, bundle_data_list):
        """
        Populate the tasks table widget from a list of dicts using only
        the desired keys.
        """

        DESIRED_COLUMNS = ["file_name", "file_id", "file_size"]
        num_rows = len(bundle_data_list)
        num_cols = len(DESIRED_COLUMNS)
        
        # Clear existing rows
        self.bundle_tableWidget.clearContents()
        self.bundle_tableWidget.setRowCount(num_rows)
        self.bundle_tableWidget.setColumnCount(num_cols)

        # Set Header Labels
        self.bundle_tableWidget.setHorizontalHeaderLabels(DESIRED_COLUMNS)

        # Populate Table
        QgsMessageLog.logMessage(message=f"{bundle_data_list[0]}", tag="AppEEARS", level=Qgis.Info)
        for row_index, entry in enumerate(bundle_data_list):
            for col_index, key in enumerate(DESIRED_COLUMNS):
                value = entry.get(key,"")
                if key == "file_name":
                    value = value.split("/")[-1]
                item = QtWidgets.QTableWidgetItem(str(value))
                self.bundle_tableWidget.setItem(row_index, col_index, item)
        # Resize
        self.bundle_tableWidget.resizeColumnsToContents()

    def load_selected_file(self):
        """
        Uses the current_task_id, file_id, and file_name to build a url path, then opens the url and adds the layer to the current project.
        Currently only works for cloud-optimized geotiff files.
        """

        # Retrieve current row
        row = self.bundle_tableWidget.currentRow()
        if row < 0:
            QgsMessageLog.logMessage(message="No file selected.", tag="AppEEARS", level=Qgis.Info)
            return

        # Get ID and Name and Open File
        try: 
            file_id = self.bundle_tableWidget.item(row,1).text()
            file_name = self.bundle_tableWidget.item(row,0).text()

            if not file_id:
                QtWidgets.QMessageBox.warning(self, "Invalid Row","Could not find task.")
                return

            # Build File URL from selection
            file_url = build_file_url(self.api_url, self.current_task_id, file_id, file_name)
            
            # Handle non-tif cases
            if file_url.split('.')[-1] != 'tif':
                self.not_supported_error()
                return

            # Set Necessary GDAL Options
            set_gdal_options(self.token)
            QgsMessageLog.logMessage(message="Required GDAL options set.", tag="AppEEARS", level=Qgis.Info)
        
            # Load data into memory
            QgsMessageLog.logMessage(message=f"Opening Data from source:  {file_url}", tag="AppEEARS", level=Qgis.Info)
            raster_layer = QgsRasterLayer(file_url, file_name)

            # Add Layer to QGIS Project
            QgsProject.instance().addMapLayer(raster_layer)
            QgsMessageLog.logMessage(message=f"Added raster layer: {file_name}", tag="AppEEARS", level=Qgis.Info)

        except Exception as e:
            QgsMessageLog.logMessage(message=f"Error loading COG. {e}", tag="AppEEARS", level=Qgis.Info)
            return None     

    def not_supported_error(self):
        """
        Displays a QMessageBox with an 'Error' for unsupported operations within QGS.
        Currently this plugin only supports AppEEARS Area requests with cloud-optimized geotiff outputs.
        """
        QtWidgets.QMessageBox.critical(self, "Error", "Currently this plugin shows all AppEEARS requests and output filetypes, but only supports opening cloud-optimized geotiff files from area sample requests.")